import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {parse} from 'parse5';import {XMLParser,XMLValidator} from 'fast-xml-parser';import {site} from '../src/config.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dist=path.join(root,'dist'),pages=JSON.parse(fs.readFileSync(path.join(root,'ops/pages.json'),'utf8')),results=[],documents=new Map();
const attr=(n,k)=>n.attrs?.find(a=>a.name===k)?.value;const all=(n,p)=>[...(p(n)?[n]:[]),...(n.childNodes||[]).flatMap(c=>all(c,p))];const text=n=>n.nodeName==='#text'?n.value:(n.childNodes||[]).map(text).join('');
function result(id,p,condition,expected,actual){results.push({rule_id:id,url:p.url,status:condition?'PASS':'FAIL',expected,actual,evidence:p.path||'index.html',checked_at:new Date().toISOString(),environment:'build-output'});}
for(const p of pages){const filename=path.join(dist,p.path.endsWith('.html')?p.path:p.path+'index.html'),html=fs.readFileSync(filename,'utf8');documents.set(p.path,{html,doc:parse(html)});}
const titles=new Set();
for(const p of pages){const {doc,html}=documents.get(p.path),main=all(doc,n=>n.tagName==='main')[0],heads=all(main,n=>/^h[1-6]$/.test(n.tagName||'')),h1=heads.filter(n=>n.tagName==='h1'),title=all(doc,n=>n.tagName==='title'),canonical=all(doc,n=>n.tagName==='link'&&attr(n,'rel')==='canonical'),robots=all(doc,n=>n.tagName==='meta'&&attr(n,'name')==='robots'),description=all(doc,n=>n.tagName==='meta'&&attr(n,'name')==='description');
result('V02',p,!!main&&text(main).trim().length>80,'Main text in initial HTML',text(main).trim().length);
result('V07',p,title.length===1&&text(title[0]).trim()&&!titles.has(text(title[0]))&&description.length===1,'Unique title and description',text(title[0]));titles.add(text(title[0]));
result('V05',p,canonical.length===1&&attr(canonical[0],'href')===p.canonical,'Canonical equals page ledger',canonical.map(n=>attr(n,'href')));
result('V03',p,robots.length===1&&(/\bnoindex\b/.test(attr(robots[0],'content'))===!p.index),'Index policy matches ledger',robots.map(n=>attr(n,'content')));
let hierarchy=true,last=1;for(const h of heads){const level=Number(h.tagName.slice(1));if(!text(h).trim()||level>last+1)hierarchy=false;last=level;}result('V19',p,h1.length===1&&hierarchy,'One nonempty h1; no skipped descending levels',heads.map(n=>n.tagName+': '+text(n).trim()));
result('V09-A11Y',p,all(doc,n=>n.tagName==='html').every(n=>attr(n,'lang')==='ja')&&all(doc,n=>n.tagName==='img').every(n=>attr(n,'alt')!==undefined&&attr(n,'width')&&attr(n,'height')),'Japanese lang; image alt and reserved dimensions','Checked all images');
const duplicates=[],ids=new Set();for(const n of all(doc,n=>!!attr(n,'id'))){const id=attr(n,'id');if(ids.has(id))duplicates.push(id);ids.add(id);}result('V19-ID',p,!duplicates.length,'Unique IDs',duplicates);
let schema=true;for(const n of all(doc,n=>n.tagName==='script'&&attr(n,'type')==='application/ld+json'))try{const value=JSON.parse(text(n));if(!value['@context']||(!value['@type']&&!(Array.isArray(value['@graph'])&&value['@graph'].length&&value['@graph'].every(node=>node['@type']))))schema=false;}catch{schema=false;}result('V08',p,schema,'JSON-LD parses with context/type','No fabricated prices or ratings in templates');
result('V12-V16',p,!/localhost|127\.0\.0\.1|株式会社サンプル|架空サンプル|[A-Z]:\\Users|taro@example/.test(html),'No development URLs/private paths/dummy facts','Scanned output HTML');
const broken=[];for(const n of all(doc,n=>n.tagName==='a'||n.tagName==='link'||n.tagName==='img'||(n.tagName==='script'&&attr(n,'src')))){const value=attr(n,n.tagName==='img'||n.tagName==='script'?'src':'href');if(!value||value.startsWith('mailto:'))continue;const resolved=new URL(value,p.url);if(resolved.origin!==site.origin)continue;if(!resolved.pathname.startsWith(site.base)){broken.push(value);continue;}const relative=decodeURIComponent(resolved.pathname.slice(site.base.length));const target=path.join(dist,relative.endsWith('/')?relative+'index.html':relative);if(!fs.existsSync(target))broken.push(value);if(resolved.hash){const targetDoc=documents.get(relative)?.doc;if(!targetDoc||!all(targetDoc,x=>attr(x,'id')===decodeURIComponent(resolved.hash.slice(1))).length)broken.push(value);}}
result('V11-LINK',p,!broken.length,'All internal targets and fragments exist',broken);
}
const xml=fs.readFileSync(path.join(dist,'sitemap.xml'),'utf8');const validXML=XMLValidator.validate(xml)===true;const map=new XMLParser().parse(xml),listed=[map.urlset?.url||[]].flat().map(x=>x.loc),expected=pages.filter(p=>p.index&&p.path!=='404.html').map(p=>p.url);result('V05-SITEMAP',{url:site.origin+site.base+'sitemap.xml',path:'sitemap.xml'},validXML&&JSON.stringify(listed.sort())===JSON.stringify(expected.sort()),'Exactly the indexed canonical URLs excluding the error page',listed.length);
fs.mkdirSync(path.join(root,'reports'),{recursive:true});fs.writeFileSync(path.join(root,'reports/aio-static.json'),JSON.stringify(results,null,2));const failures=results.filter(r=>r.status==='FAIL');console.log(JSON.stringify({pages:pages.length,checks:results.length,failures},null,2));if(failures.length)process.exitCode=1;
