import {blogPosts,newsPosts} from './updates.mjs';
import {site,url,absolute} from './config.mjs';
import {services,packages,works,topics,faqs} from './content.mjs';
export const escape = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escape;
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const logo=(white=false)=>`<img src="${url('assets/logo.png')}" alt="OneBe" width="156" height="38" ${white?'class="logo-white"':''}>`;
const btn=(label,href,kind='',attrs='')=>`<a class="button ${kind}" href="${e(href)}" ${attrs}>${e(label)}${arrow}</a>`;
const link=(label,href)=>`<a class="text-link" href="${e(href)}">${e(label)}${arrow}</a>`;
const photo=(name,alt='',cls='',priority=false)=>`<img class="${cls}" src="${url('assets/'+name+'.webp')}" alt="${e(alt)}" width="1200" height="800" loading="${priority?'eager':'lazy'}" decoding="async" ${priority?'fetchpriority="high"':''}>`;
const eyebrow=s=>`<p class="eyebrow">${e(s)}</p>`;
const heading=(en,ja,desc='')=>`${eyebrow(en)}<h2>${ja}</h2>${desc?`<p class="lead">${desc}</p>`:''}`;
const contactLink=topic=>url('contact/')+(topic?'?topic='+encodeURIComponent(topic):'');
const steps=(short=false)=>`<ol class="steps ${short?'vertical':''}">${(short?['内容を確認','お話を伺う','進め方をご相談']:['お話を聞く','課題と範囲を整理','方向性をご提案','制作・実行','納品・公開']).map((s,i)=>`<li><span class="step-num">${String(i+1).padStart(2,'0')}</span><span>${s}</span></li>`).join('')}</ol>`;
const faq=()=>`<section class="section container faq-section" id="faq">${heading('FAQ','ご相談の前に。')}<div class="faq-list">${faqs.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">＋</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
const cta=()=>`<section class="contact-band"><div class="container contact-band-inner"><div class="band-logo">${logo(true)}</div><div><h2>会社や事業のこれからを、<br>一緒に整理しませんか。</h2><p>課題がまとまっていない段階でも、お話を聞かせてください。</p></div>${btn('ブランドについて相談する',contactLink(),'light')}</div></section>`;
function header(active){return `<a class="skip-link" href="#main-content">本文へスキップ</a><header class="site-header"><div class="header-inner"><a class="brand" href="${url()}" aria-label="OneBe ホーム">${logo()}</a><nav class="desktop-nav" aria-label="主要ナビゲーション">${[['','ホーム'],['works/','実績'],['services/','支援内容'],['about/','OneBeについて']].map(([r,s])=>`<a href="${url(r)}" ${active===r?'aria-current="page"':''}>${s}</a>`).join('')}</nav>${btn('ブランドについて相談する',contactLink(),'header-contact')}<a class="mobile-contact" href="${contactLink()}">ご相談</a><button class="menu-toggle icon-button" type="button" data-open="menu" aria-label="メニューを開く" aria-haspopup="dialog" aria-controls="menu-dialog"><span></span><span></span></button></div></header>`;}
const footer=()=>`<footer class="site-footer"><div class="container footer-top"><a href="${url()}" aria-label="OneBe ホーム">${logo()}</a><nav aria-label="フッターナビゲーション">${[['works/','実績'],['services/','支援内容'],['about/','OneBeについて'],['contact/','ご相談'],['privacy/','プライバシーポリシー']].map(([r,s])=>`<a href="${url(r)}">${s}</a>`).join('')}</nav></div><div class="container footer-bottom"><a href="mailto:${site.email}">${site.email}</a><small>© ${new Date(site.updated).getFullYear()} OneBe</small></div></footer>`;
function dialog(id,title,body,cls=''){return `<dialog id="${id}-dialog" aria-labelledby="${id}-title" class="dialog ${cls}"><div class="dialog-inner"><div class="dialog-top"><h2 id="${id}-title">${title}</h2><button class="icon-button close-dialog" type="button" aria-label="閉じる"><span aria-hidden="true">×</span></button></div>${body}</div></dialog>`;}
const commonDialogs=()=>dialog('menu','MENU',`<nav class="menu-links" aria-label="モバイルナビゲーション">${[['','ホーム'],['works/','実績'],['services/','支援内容'],['about/','OneBeについて']].map(([r,s])=>`<a href="${url(r)}">${s}${arrow}</a>`).join('')}${btn('ブランドについて相談する',contactLink())}</nav>`,'menu-dialog')+dialog('image','実績画像','<img id="zoom-image" src="'+url('assets/umui-business-cards.webp')+'" alt="" width="1200" height="800"><p id="zoom-caption" class="caption"></p>','image-dialog');
const loadingIntro=script=>script?`<dialog id="intro-loader" aria-labelledby="intro-title"><p id="intro-title" class="intro-label">OneBeのオープニング</p><video data-src="${url('assets/onebe-loading-v2.mp4')}" width="1920" height="1080" muted playsinline preload="none" aria-hidden="true" tabindex="-1"></video><button type="button" class="intro-skip" aria-label="動画をスキップしてサイトを表示">スキップ${arrow}</button></dialog><script>${script.replace(/<\/script/gi,'<\\/script')}</script>`:'';
export function layout(page,body,introScript=''){
  const canonical=absolute(page.path),title=page.title+(page.path?'｜OneBe':'');
  const organization={'@context':'https://schema.org','@type':'Organization','@id':absolute()+'#organization',name:'OneBe',url:absolute(),email:site.email,logo:absolute('assets/logo.png')};
  const schemas=[];if(!page.path)schemas.push(organization);
  if(page.service)schemas.push({'@context':'https://schema.org','@type':'Service','@id':canonical+'#service',name:page.title,description:page.description,url:canonical,provider:{'@type':'Organization',name:'OneBe',url:absolute()}});
  if(page.path&&!page.noindex)schemas.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'ホーム',item:absolute()},{'@type':'ListItem',position:2,name:page.title,item:canonical}]});
  return `<!doctype html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(page.description)}"><link rel="canonical" href="${canonical}"><meta name="robots" content="${page.noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(page.description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="OneBe"><meta name="theme-color" content="#111936"><link rel="icon" href="${url('assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('assets/site.css')}?v=${site.updated}">${schemas.map(s=>`<script type="application/ld+json">${JSON.stringify(s).replace(/</g,'\\u003c')}</script>`).join('')}<script type="module" src="${url('assets/site.js')}?v=${site.updated}"></script></head><body data-base="${site.base}" data-route="${e(page.path)}" data-form-endpoint="${site.formEndpoint}">${loadingIntro(introScript)}${header(page.active)}<main id="main-content">${page.path?`<div class="container breadcrumbs"><a href="${url()}">ホーム</a><span aria-hidden="true">/</span><span>${e(page.title)}</span></div>`:''}${body}</main>${footer()}${commonDialogs()}</body></html>`;
}
const hero=(en,title,description,image)=>`<section class="page-hero container ${image?'split':''}"><div>${eyebrow(en)}<h1>${title}</h1><p class="lead">${description}</p></div>${image?photo(image,'','hero-image',true):''}</section>`;
function workCard(w,featured=false){return `<article class="work-card ${featured?'featured':''}" data-categories="${e(w.categories.join('|'))}"><a href="${url('works/'+w.id+'/')}" class="work-image" tabindex="-1" aria-hidden="true">${photo(w.image,w.imageAlt)}<span class="image-note">${e(w.imageLabel)}</span></a><div class="work-copy"><p class="work-name">${w.name}</p><h3>${w.title}</h3><p class="caption">${w.scope}</p>${link('成果を見る',url('works/'+w.id+'/'))}</div></article>`;}
function philosophy(){return `<section class="section pale"><div class="container"><div class="section-intro">${heading('PHILOSOPHY','本音から、<br>ブランドをつくる。')}<p>大切にしてきたこと。うまく伝わっていないこと。<br>これから挑戦したいこと。<br>まずは、会社や事業のお話を聞かせてください。</p></div><div class="values-grid">${[['聞く','実際の想いや課題を、丁寧に聞きます。'],['整理する','言葉にし、伝える軸をつくります。'],['形にする','最適な表現で、社会に届けます。']].map(([t,b],i)=>`<div><span class="big-num">0${i+1}</span><div><h3>${t}</h3><p>${b}</p></div></div>`).join('')}</div><div class="align-right">${link('OneBeの考え方を知る',url('about/'))}</div></div></section>`;}

const dateLabel=value=>value.replaceAll('-','.');
const newsRows=posts=>`<ul class="news-list">${posts.map(n=>`<li><a href="${url('news/'+n.id+'/')}"><time datetime="${e(n.date)}">${dateLabel(n.date)}</time><span class="news-category">${e(n.category)}</span><span class="news-title">${e(n.title)}</span>${arrow}</a></li>`).join('')}</ul>`;
function homeUpdates(){return `<section class="section container home-blog" id="blog"><div class="section-title-row"><div>${heading('BLOG','OneBeの視点。')}<p class="lead">代表のnoteから、仕事への想いやデザインの背景をお届けします。</p></div>${link('ブログ一覧を見る（note）','https://note.com/isseimasuya')}</div><div class="blog-grid">${blogPosts.slice(0,3).map(p=>`<article class="blog-card"><a href="${e(p.href)}"><div class="blog-image"><img src="${e(p.image)}" alt="" width="800" height="420" loading="lazy" decoding="async"></div><p class="post-meta"><time datetime="${e(p.date)}">${dateLabel(p.date)}</time><span>${e(p.category)}</span></p><h3>${e(p.title)}</h3><span class="blog-read">noteで読む ${arrow}</span></a></article>`).join('')}</div></section><section class="section pale home-news" id="news"><div class="container news-layout"><div>${heading('NEWS','お知らせ。')}${link('ニュース一覧を見る',url('news/'))}</div>${newsRows(newsPosts.slice(0,3))}</div></section>`;}
function newsIndex(){return `${hero('NEWS','お知らせ。','株式会社OneBeからのお知らせを掲載しています。')}<section class="section container news-index">${newsRows(newsPosts)}<p class="lead">OneBeの仕事への想いや代表の歩みは、ブログでもご紹介しています。</p>${link('代表のnoteを読む','https://note.com/isseimasuya')}</section>${cta()}`;}
function newsDetail(n){return `<article class="section container news-article">${eyebrow('NEWS')}<p class="post-meta"><time datetime="${e(n.date)}">${dateLabel(n.date)}</time><span>${e(n.category)}</span></p><h1>${e(n.title)}</h1><p class="news-author">株式会社OneBe</p><div class="news-body">${n.body.map(p=>`<p>${e(p)}</p>`).join('')}</div>${link('ブログを読む',url('#blog'))}<div class="news-back">${link('ニュース一覧に戻る',url('news/'))}</div></article>${cta()}`;}

export function home(){return `<section class="home-hero"><div class="hero-copy">${eyebrow('BRANDING & DESIGN')}<p class="hero-statement">本気の想いを、<br>本気で伝える。</p><h1>想いをかたちにする、<br>OneBeのブランディング・デザイン</h1><p>会社や事業の想いを整理し、言葉とデザインで伝わる形へ。<br>ブランドの方向づくりから、その実現に伴走します。</p><div class="hero-actions">${btn('ブランドについて相談する',contactLink())}${link('実績を見る',url('works/'))}</div></div><div class="hero-visual hero-film"><picture class="hero-poster"><source media="(max-width:767px)" srcset="${url('assets/hero-type-mobile.webp')}"><source media="(max-width:1199px)" srcset="${url('assets/hero-type-tablet.webp')}"><img src="${url('assets/hero-type-pc.webp')}" alt="想いを綴った明朝体の言葉とOneBeのロゴ" width="1200" height="1000" fetchpriority="high"></picture><video id="hero-video" data-pc="${url('assets/hero-type-pc.mp4')}" data-tablet="${url('assets/hero-type-tablet.mp4')}" data-mobile="${url('assets/hero-type-mobile.mp4')}" muted playsinline loop preload="none" aria-hidden="true" tabindex="-1" hidden></video><button id="hero-playback" type="button" aria-label="FVの映像を一時停止" hidden>一時停止</button></div></section><div class="manifesto"><p>本音を聞く。 <span>想いを整理する。</span> 伝わる形にする。</p></div><section class="section container" id="works"><div class="section-title-row"><div>${heading('WORKS','想いを、事業の現場へ。','会社や事業ごとに異なる課題に向き合い、言葉、Web、紙、空間へ。')}</div>${link('すべての実績を見る',url('works/'))}</div>${workCard(works[0],true)}<div class="work-grid home-works">${works.slice(1).map(w=>workCard(w)).join('')}</div></section>${philosophy()}<section class="section container"><div class="section-title-row"><div>${heading('SERVICES','方向性を考えるところから、<br>伝える形まで。')}</div>${link('支援内容を見る',url('services/'))}</div><div class="support-grid">${[['想いと方向性を整理する','強みや理念をうまく説明できない方へ。','ヒアリング／理念の言語化／伝える方針の整理'],['伝わる形をつくる','Webや会社案内を見直したい方へ。','Web／紙／広告・サイン／店舗'],['表現を監修する','発信や制作物の方向性を揃えたい方へ。','制作物・メディアの表現監修']].map(([a,b,c],i)=>`<article><span class="big-num">0${i+1}</span><h3>${a}</h3><p>${b}</p><p class="caption">${c}</p></article>`).join('')}</div></section><section class="section container process-section">${heading('PROCESS','まず、事業のお話から。')}${steps()}</section><section class="section container about-teaser">${photo('dialogue','対話する場面のイメージ')}<div>${heading('ABOUT','想いに向き合う人がいる。','どんなに小さな想いでも、それはきっと、誰かの未来につながっています。OneBeは、想いに向き合い、ともに考え、伝わる形をつくるパートナーでありたいと考えています。')}${btn('OneBeについて',url('about/'))}</div></section>${homeUpdates()}${cta()}`;}
export function workIndex(){return `${hero('WORKS','想いがつくってきた、実績。','会社や事業の想いと向き合い、それぞれに必要な形へ。OneBeが関わった仕事をご紹介します。')}<section class="section container works-section" aria-labelledby="works-heading"><h2 id="works-heading" class="small-heading">制作・支援実績</h2><div class="filter-bar" role="group" aria-label="実績を絞り込む">${['すべて','Web','紙・サイン','空間','ブランド'].map((s,i)=>`<button class="filter ${i===0?'active':''}" type="button" data-filter="${s}" aria-pressed="${i===0}">${s}</button>`).join('')}<span class="result-count" aria-live="polite">${works.length}件の実績</span></div><div id="works-grid">${workCard(works[0],true)}<div class="work-grid">${works.slice(1).map(w=>workCard(w)).join('')}</div></div><p id="no-results" hidden>該当する実績はありません。別のカテゴリーをお選びください。</p></section>${cta()}`;}
const workFigure=(image,alt,caption,priority=false)=>`<figure><button class="zoom-trigger" type="button" data-zoom="${url('assets/'+image+'.webp')}" data-caption="${e(caption)}" aria-label="${e(alt)}を拡大">${photo(image,alt,'',priority)}<span>画像を拡大 ${arrow}</span></button><figcaption>${e(caption)}</figcaption></figure>`;
export function workDetail(w){return `${hero('WORKS / '+w.name,w.title,w.name+'｜'+w.scope)}<article class="container work-detail">${workFigure(w.image,w.imageAlt,w.imageCaption,true)}<section class="section editorial"><div>${heading('SCOPE','OneBeが担当したこと。')}</div><div><p class="large-copy">${w.description}</p><dl class="facts"><div><dt>名称</dt><dd>${w.name}</dd></div><div><dt>担当範囲</dt><dd>${w.scope}</dd></div></dl></div></section>${w.gallery.length?`<section class="work-gallery-section" aria-label="${e(w.name)}の事業の現場"><div class="work-gallery">${w.gallery.map(g=>workFigure(g.image,g.alt,g.caption)).join('')}</div></section>`:''}<div class="detail-navigation">${link('実績一覧へ戻る',url('works/'))}${btn('同じようなことを相談する',contactLink('まだ決まっていない'))}</div></article>${cta()}`;}
export function servicesIndex(){return `${hero('SERVICES','想いに合わせて、<br>必要な支援を。','「何をつくるか」からでも、「何から始めるか」からでも。事業の目的と状況に合わせて、一緒に考えます。','serviceHero')}<nav class="container anchor-nav" aria-label="支援内容の目次">${[['issue','何から始めるか相談'],['creative','つくるものから選ぶ'],['packages','パッケージ・サービス'],['process','進め方'],['faq','よくあるご質問']].map(([id,s])=>`<a href="#${id}">${s}<span>↓</span></a>`).join('')}</nav><section class="section pale" id="issue"><div class="container consultation-split"><div>${heading('START WITH A CONVERSATION','何をつくるか、<br>決まっていなくても。','「会社の強みがうまく伝わらない」「Webや会社案内を見直したいけれど、何から始めればいいか分からない」。そんな段階からご相談いただけます。')}<p>事業の現状や大切にしている想いを伺い、誰に何を伝えるか、どこから取り組むかを一緒に整理します。</p>${btn('何から始めるか相談する',contactLink('まだ決まっていない'))}</div>${photo('dialogue','事業の課題を話し合う場面のイメージ')}</div></section><section class="section container" id="creative">${heading('CREATIVE MENU','つくるものから選ぶ。','必要なものが決まっている方も、まずは使う場面や目的をお聞かせください。')}<div class="service-grid">${services.map(s=>`<article class="service-card">${photo(s.image)}<p class="eyebrow">${s.en}</p><h3><a href="${url('services/'+s.id+'/')}" data-open="service-${s.id}">${s.name}</a></h3><p>${s.when}</p><a class="text-link" href="${url('services/'+s.id+'/')}" data-open="service-${s.id}" aria-haspopup="dialog">対応内容を見る${arrow}</a></article>`).join('')}</div></section><section class="section pale" id="packages"><div class="container">${heading('PACKAGES & SERVICES','目的に合わせた、<br>パッケージとサービス。','事業の立ち上げ、Webの活用、新しいお客様との接点づくりに。')}<div class="package-grid">${packages.map(p=>`<article class="package-card">${photo(p.image)}<div class="package-copy">${eyebrow(p.en)}<h3>${p.name}</h3><p>${p.description}</p>${link(p.name+'を見る',url('services/'+p.id+'/'))}</div></article>`).join('')}</div></div></section><section class="section container process-section" id="process">${heading('PROCESS','まず、事業のお話から。','目的と必要な範囲を整理してから、制作を進めます。')}${steps()}<p class="process-note">費用・納期・対応範囲は、ご依頼前にすり合わせます。</p></section>${faq()}${cta()}${services.map(s=>dialog('service-'+s.id,s.name,`${photo(s.image)}<p class="large-copy">${s.when}</p><p>${s.description}</p><ul>${s.scope.map(x=>`<li>${x}</li>`).join('')}</ul><p class="caption">費用・納期は必要な内容と範囲に合わせてお見積もりします。</p>${btn('この内容で相談する',contactLink(s.topic))}${link(s.name+'の支援内容を読む',url('services/'+s.id+'/'))}`)).join('')}`;}
export function serviceDetail(s){return `${hero(s.en,s.name+'で、<br>想いを伝わる形へ。',s.when,s.image)}<section class="section container editorial"><div>${heading('WHAT WE DO','対応できること。')}</div><div><p class="large-copy">${s.description}</p><ul class="scope-list">${s.scope.map(x=>`<li>${x}</li>`).join('')}</ul></div></section><section class="section pale"><div class="container editorial"><div>${heading('SCOPE & ESTIMATE','必要な範囲を、<br>一緒に決める。')}</div><div><p>目的、現在の状況、使用する場面、ご希望の時期を伺います。制作する内容と役割分担を確認し、お見積もりとスケジュールをご提案します。</p><p>印刷・施工・撮影などの手配が必要な場合は、対応の可否と費用を個別に確認します。</p>${btn(s.name+'について相談する',contactLink(s.topic))}</div></div></section><section class="section container process-section">${heading('PROCESS','ご相談から、制作まで。')}${steps()}${link('支援内容の一覧へ戻る',url('services/'))}</section>${faq()}${cta()}`;}
export function packageDetail(p){return `${hero(p.en,p.name+'<br><span class="hero-sub">'+p.lead+'</span>',p.description,p.image)}<section class="section pale"><div class="container editorial"><div>${heading('FOR YOU','こんなときに、<br>ご相談ください。')}</div><p class="large-copy">${p.for}</p></div></section><section class="section container editorial"><div>${heading('SUPPORT','支援の組み立て。')}</div><div><ol class="scope-list">${p.points.map(x=>`<li>${x}</li>`).join('')}</ol><h3>対象範囲・料金・契約条件</h3><p>${p.conditions}</p>${btn(p.name+'について相談する',contactLink(p.name))}</div></section><section class="section container process-section">${heading('PROCESS','まずは、目的と必要な範囲から。')}${steps()}${link('支援内容の一覧へ戻る',url('services/'))}</section>${cta()}`;}
export function about(){return `${hero('ABOUT ONEBE','本気の想いに、<br>本気で向き合う。','OneBeは、会社や事業の想いを整理し、言葉とデザインで伝えるパートナーです。','aboutHero')}<section class="section container editorial"><div>${heading('OUR MISSION','本気の想いを、<br>本気で伝える。')}</div><div><p class="large-copy">いい仕事がある。<br>大切にしている想いがある。<br>その価値が、必要な人に届くように。</p><p>言葉にしきれていない気持ちや、当たり前になっている強みに向き合い、伝わる形をともにつくります。</p></div></section><section class="section pale"><div class="container editorial"><div>${heading('OUR VISION','本気の仕事で<br>あふれる社会の実現。')}</div><div><h3>本音で話す。</h3><p>取り繕うより、実際の想いを聞くこと。立場を越えて、事業にとって必要なことを話します。</p><h3>まずやる。</h3><p>考えるだけで終わらず、形にしてみること。やってみたからこそ分かることを、次の一歩につなげます。</p></div></div></section><section class="section container representative" id="representative"><div class="portrait-wrap">${photo('portrait','OneBe代表 舛谷一成','portrait')}</div><div>${heading('REPRESENTATIVE','想いに向き合う人がいる。')}<p class="person-role">OneBe 代表</p><h3 class="person-name">舛谷 一成 <span>ISSEI MASUYA</span></h3><p>青森市出身。学生時代のイベント企画や、接客・コールセンター管理などの仕事を経て、映像制作で独立。その後、デザイン、Web、ブランドづくりへと活動を広げてきました。</p><p>どんなに小さな想いでも、それはきっと、誰かの未来につながっています。事業や人の背景にある想いに向き合い、ともに考え、伝わる形をつくる。その積み重ねを大切にしています。</p>${btn('代表のプロフィールを読む',site.profile,'secondary','target="_blank" rel="noopener noreferrer"')}</div></section><section class="section container editorial"><div>${heading('INFORMATION','OneBeについて。')}</div><dl class="facts"><div><dt>名称</dt><dd>株式会社OneBe</dd></div><div><dt>代表</dt><dd>舛谷 一成</dd></div><div><dt>事業内容</dt><dd>ブランディング支援、Web・グラフィック・店舗等のデザイン、表現の監修</dd></div><div><dt>お問い合わせ</dt><dd><a href="mailto:${site.email}">${site.email}</a></dd></div></dl></section>${cta()}`;}
const field=(id,label,type='text',optional=false)=>`<div class="field"><label for="${id}">${label}<span class="badge">${optional?'任意':'必須'}</span></label><input id="${id}" name="${id}" type="${type}" ${optional?'':'required'} maxlength="${id==='email'?254:100}" autocomplete="${id==='company'?'organization':id}" aria-describedby="${id}-error"><p class="field-error" id="${id}-error"></p></div>`;
export function contact(){return `${hero('CONTACT','まだ、うまく話せなくても<br>大丈夫です。','事業のこと、伝え方のこと、これからのこと。今、気になっていることからお聞かせください。')}<section class="section container contact-layout"><aside><h2>OneBeへのご相談</h2><p>まとまっていない想いや課題も、そのままお書きください。</p><h3>ご相談後の流れ</h3>${steps(true)}<a class="email-link" href="mailto:${site.email}">${site.email}</a></aside><form id="contact-form" class="contact-form" novalidate><div id="form-errors" class="error-summary" role="alert" tabindex="-1" hidden></div><p class="topic-notice" id="topic-notice" hidden></p>${field('company','会社名・屋号','text',true)}${field('name','お名前')}${field('email','メールアドレス','email')}<fieldset class="topic-field"><legend>相談したいこと<span class="badge">必須</span></legend><p class="field-hint">複数選択できます。迷ったら「まだ決まっていない」をお選びください。</p><div class="checkbox-grid">${topics.map((s,i)=>`<label><input type="checkbox" name="topics" value="${s}" id="topic-${i}" aria-describedby="topics-error"><span>${s}</span></label>`).join('')}</div><p class="field-error" id="topics-error"></p></fieldset><div class="field"><label for="message">ご相談内容<span class="badge">必須</span></label><p class="field-hint">今のお悩みや、やってみたいことを自由にお書きください。</p><textarea id="message" name="message" required maxlength="5000" rows="7" aria-describedby="message-error message-count"></textarea><p class="field-error" id="message-error"></p><p id="message-count" class="field-hint align-right">0 / 5,000</p></div><div class="field"><label for="budget">ご予算の目安<span class="badge">任意</span></label><select name="budget" id="budget"><option>未定・相談したい</option><option>相談内容に記載する</option></select></div><div class="honeypot" aria-hidden="true"><label>この欄には入力しないでください<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="consent"><label><input type="checkbox" name="consent" id="consent" required aria-describedby="consent-error"><span><a href="${url('privacy/')}" target="_blank" rel="noopener">プライバシーポリシー</a>に同意する</span></label><p class="field-error" id="consent-error"></p></div><p class="field-hint">お問い合わせの送信にはFormSubmitを利用します。</p><button class="button" type="submit">入力内容を確認する${arrow}</button><p class="field-hint align-center">この時点では送信されません。</p><noscript><p>フォームにはJavaScriptが必要です。メールでもご相談いただけます：<a href="mailto:${site.email}">${site.email}</a></p></noscript></form></section>${faq()}`;}
export function confirm(){return `${hero('CONFIRM','ご相談内容をご確認ください。','修正する場合は「入力内容を修正する」から戻れます。')}<section class="section container narrow"><div id="missing-draft" hidden><p>入力内容が見つかりません。相談フォームからご入力ください。</p>${btn('相談フォームへ',contactLink())}</div><div id="confirmation"><h2 class="small-heading">送信する内容</h2><dl class="facts confirmation-facts" id="confirmation-values"></dl><p class="field-hint">プライバシーポリシーに同意済み</p><div id="send-error" class="error-summary" role="alert" tabindex="-1" hidden></div><button class="button full" id="send-button" type="button">この内容で送信する${arrow}</button><a class="button secondary full" href="${contactLink()}" id="edit-link">入力内容を修正する${arrow}</a><p id="sending-status" role="status" class="field-hint"></p></div><noscript><p>確認と送信にはJavaScriptが必要です。<a href="mailto:${site.email}">メールでご相談ください。</a></p></noscript></section>`;}
export function thanks(){return `<section class="thanks-hero warm"><div class="container narrow"><div class="envelope" aria-hidden="true"><svg viewBox="0 0 80 64"><path d="M5 14h70v44H5zM5 14l35 28 35-28M5 58l24-23m46 23L51 35"/></svg><span>✓</span></div>${eyebrow('THANK YOU')}<h1>ご相談いただき、<br>ありがとうございます。</h1><p class="thanks-message">OneBeを見つけてくださったこと。<br>そして、お話を聞かせようと<br class="mobile-only">思ってくださったこと。<br>そのご縁を、うれしく思います。</p><p class="thanks-promise">いただいた想いに、<br>本気で向き合います。</p></div></section><section class="section container narrow"><div class="receipt" id="receipt" hidden><h2>ご相談の送信を受け付けました。</h2><p>内容を確認のうえ、ご入力いただいたメールアドレスへご連絡いたします。</p></div><div id="thanks-direct"><p>ご相談はフォームからお送りいただけます。</p>${btn('ブランドについて相談する',contactLink())}</div><div class="section">${heading('NEXT','このあとの流れ。')}${steps(true)}</div>${heading('DISCOVER ONEBE','よろしければ、<br>OneBeのことをもう少し。')}<div class="next-links">${btn('実績・成果を見る',url('works/'),'secondary')}${btn('OneBeについて',url('about/'),'secondary')}</div>${link('ホームへ戻る',url())}</section>`;}
export function privacy(){return `${hero('PRIVACY','プライバシーポリシー','OneBeへのお問い合わせにおける、個人情報の取扱いについて。')}<article class="section container narrow prose"><section><h2>取得する情報と利用目的</h2><p>お問い合わせフォームでは、会社名・屋号、お名前、メールアドレス、ご相談内容、予算の目安をお預かりします。これらの情報は、ご相談への回答、ご提案、ご依頼に関する連絡のために利用します。</p></section><section><h2>外部サービスの利用</h2><p>フォームの送信にはFormSubmitを利用します。入力した内容は同サービスを経由し、OneBeの窓口（${site.email}）に送られます。同サービスによる情報の取扱いは、<a href="https://formsubmit.co/privacy.pdf" target="_blank" rel="noopener noreferrer">FormSubmitのプライバシーポリシー</a>をご確認ください。</p><p>サイトはGitHub Pagesで配信しています。配信事業者によるアクセス情報等の取扱いについては、<a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener noreferrer">GitHubのプライバシーステートメント</a>をご確認ください。</p></section><section><h2>入力内容の一時保存</h2><p>入力内容の確認・修正のため、このブラウザのタブ内に入力を一時保存します。送信完了時に削除し、未送信の内容も24時間を過ぎたものは次回読み込み時に破棄します。また、オープニング動画を繰り返し表示しないため、このタブ内に表示済みの情報を保存します。共有端末をご利用の場合は、使用後にタブを閉じてください。</p></section><section><h2>お問い合わせと訂正のご連絡</h2><p>情報の訂正・削除や、個人情報の取扱いに関するお問い合わせは、<a href="mailto:${site.email}">${site.email}</a>へご連絡ください。</p></section><p class="caption">運営：OneBe／制定日：2026年9月14日</p>${link('相談フォームへ',contactLink())}</article>`;}
export function notFound(){return `${hero('404 / NOT FOUND','お探しのページが<br>見つかりませんでした。','URLが変更されたか、ページが存在しない可能性があります。')}<section class="section container">${btn('ホームへ戻る',url())}${link('支援内容を見る',url('services/'))}</section>`;}
export function pageDefinitions(){return [
  {path:'news/',title:'お知らせ',description:'株式会社OneBeからのお知らせ。サイトの更新や活動に関する情報をご案内します。',render:newsIndex},
  ...newsPosts.map(n=>({path:'news/'+n.id+'/',title:n.title,description:n.body[0],render:()=>newsDetail(n)})),
  {path:'',title:'OneBe｜ブランディング・Web・グラフィックデザイン',description:'会社や事業の想いを整理し、言葉とデザインで伝わる形へ。OneBeはブランドの方向づくりからWeb、印刷物、店舗の表現まで伴走します。',render:home,active:''},
  {path:'works/',title:'制作・支援実績',description:'UMUI、そよかぜ、VAIZOなど、OneBeの制作・支援実績。ブランドの想いをWeb、紙、店舗などへ展開した担当範囲をご紹介します。',render:workIndex,active:'works/'},
  {path:'services/',title:'支援内容・サービス',description:'ブランドの方向性、ロゴ、Web、印刷物、サイン、店舗の表現監修。創業パッケージ、定額Webサービス、OneBeレターもご相談いただけます。',render:servicesIndex,active:'services/'},
  {path:'about/',title:'OneBeについて',description:'本気の想いを、本気で伝える。OneBeの考え方、代表・舛谷一成のプロフィール、事業内容とお問い合わせ先をご紹介します。',render:about,active:'about/'},
  {path:'contact/',title:'ブランド・デザインのご相談',description:'つくるものが決まっていなくても大丈夫です。事業や伝え方のお悩み、Web・ロゴ・印刷物などのご相談をOneBeへお聞かせください。',render:contact},
  {path:'contact/confirm/',title:'入力内容の確認',description:'OneBeへのお問い合わせ内容を確認して送信します。',render:confirm,noindex:true},
  {path:'thanks/',title:'ご相談ありがとうございます',description:'OneBeへのご相談後の流れと、OneBeを知るためのご案内。',render:thanks,noindex:true},
  {path:'privacy/',title:'プライバシーポリシー',description:'OneBeへのお問い合わせでお預かりする情報、利用目的、外部サービス、入力の一時保存、お問い合わせ先について。',render:privacy},
  ...works.map(w=>({path:'works/'+w.id+'/',title:w.name+'の制作・支援実績',description:w.description,render:()=>workDetail(w),active:'works/'})),
  ...services.map(s=>({path:'services/'+s.id+'/',title:s.name,description:s.description,render:()=>serviceDetail(s),active:'services/',service:true})),
  ...packages.map(p=>({path:'services/'+p.id+'/',title:p.name,description:p.description,render:()=>packageDetail(p),active:'services/',service:true})),
  {path:'404.html',title:'ページが見つかりません',description:'お探しのページが見つかりませんでした。OneBeのホームや支援内容からお探しください。',render:notFound,noindex:true}
];}
